### ISSUE TITLE
Fail to start: kivy parameters not supported?

### ISSUE THREAD

**Issue by Sektor527** [exposit/pythia-oracle#2]
When I try to run the pythia-oracle, I get the following log and crash report:

```
[INFO              ] [Logger      ] Record log in C:\Users\wvanherle\.kivy\logs\kivy_16-08-30_0.txt
[INFO              ] [Kivy        ] v1.9.1
[INFO              ] [Python      ] v3.4.4 |Anaconda 2.2.0 (64-bit)| (default, Feb 16 2016, 09:54:04) [MSC v.1600 64 bit (AMD64)]
[INFO              ] [Factory     ] 179 symbols loaded
[INFO              ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO              ] [Text        ] Provider: sdl2
[INFO              ] [OSC         ] using <thread> for socket
[INFO              ] [Window      ] Provider: sdl2
[INFO              ] [GL          ] GLEW initialization succeeded
[INFO              ] [GL          ] OpenGL version <b'4.3.0 - Build 20.19.15.4352'>
[INFO              ] [GL          ] OpenGL vendor <b'Intel'>
[INFO              ] [GL          ] OpenGL renderer <b'Intel(R) HD Graphics 4400'>
[INFO              ] [GL          ] OpenGL parsed version: 4, 3
[INFO              ] [GL          ] Shading version <b'4.30 - Build 20.19.15.4352'>
[INFO              ] [GL          ] Texture max size <16384>
[INFO              ] [GL          ] Texture max units <32>
[INFO              ] [Shader      ] fragment shader: <b"WARNING: 0:7: '' :  #version directive missing">
[INFO              ] [Shader      ] vertex shader: <b"WARNING: 0:7: '' :  #version directive missing">
[INFO              ] [Window      ] auto add sdl2 input provider
[INFO              ] [Window      ] virtual keyboard not allowed, single mode, not docked

 Traceback (most recent call last):
   File "C:\devpersonal\pythia-oracle\pythia.py", line 344, in <module>
     OracleApp().run()
   File "C:\Users\wvanherle\AppData\Local\Continuum\Anaconda3\lib\site-packages\kivy\app.py", line 802, in run
     root = self.build()
   File "C:\devpersonal\pythia-oracle\pythia.py", line 333, in build
     screenmanager.transition = SlideTransition(duration=1,clearcolor=(primary[0], primary[1], primary[2], 1), direction="left")
   File "kivy\_event.pyx", line 254, in kivy._event.EventDispatcher.__init__ (kivy\_event.c:4895)
 TypeError: object.__init__() takes no parameters

```

Doing a bit of research, I found out that this `TypeError` occurs because some `**kwargs` were not eaten by the kivy functions in the call stack. In this particular case, I believe it was the `clearcolor` parameter of `SlideTransition` (if I removed this parameter, and many more that followed, eventually I got the program to at least show the startup screen).

**Comment by exposit** [comment]
That is so weird -- oh, I see! You're using Python 3? Yes, I ran into similar issues which is why I dropped back to Python 2.7. Well, that and I think 2.7 is generally already installed on Macs so I thought it'd be simpler for those on Macs, at least.

If you look at the top of the TitleScreen class this line:

`# super().__init__(**kwargs)`

Was part of my attempts to move to 3 (but wasn't really that successful). Ultimately, though, I decided to focus on 2 since it's so widely adopted. If Kivy moves to 3 I'll have to too!

Edit, Also, it looks like Kivy does support 3.3+ [in their faq](https://kivy.org/docs/faq.html#does-kivy-support-python-3-x). So it might even be a reasonably simple fix, I'll dig around in it a bit as I can today.

**Comment by Sektor527** [comment]
Using the Anaconda distribution of Python, it's easy for me to create an environment based on Python 2.7 -- so I did that, reinstalled Kivy in that environment and tried to run Pythia again... unfortunately with the same result.

But what is strange, is that even with that environment activated (and I can verify it by invoking `python --version` and getting `Python 2.7.12 :: Continuum Analytics, Inc.` as a result), running Pythia will still report using Python 3.4.4 in its startup log.

Unfortunately, my expertise with Python only goes so far -- I have no idea where to look to find out if it's Kivy or Pythia that's somehow forcing to use my standard installed Anaconda version and not the activated conda environment (which is basically just a more convenient way to change the PATH environment variable).

**Comment by exposit** [comment]
I've never worked with Anaconda, but I can replicate the issue in 3 for sure. But not figure out how to fix it!

I don't think Pythia does anything to choose a specific version of Python, though. The first line at the top, the `#!/usr/bin/python` might be pointing somewhere off but AFAIK that doesn't do anything unless you activate it with ./ instead of python. Does it help to change that to your path or remove it or to append 2.7 to the end? Do you need to explicitly install kivy in your 2.7 environment somehow? `pip -V` should tell you which environment your pip is using.

Are you on Windows? If so, maybe try running it via doubleclick or changing the parameters of the shortcut?

Only other thing I can think of if, if explicitly installing kivy under the new python doesn't help, is maybe something like this:

http://stackoverflow.com/questions/28436769/how-to-change-default-anaconda-python-environment

I'll brew up anaconda and see if I get the same issue!

**Comment by exposit** [comment]
Ok, I cask installed anaconda 4.1.1 with Python 3, then used the instructions [here](http://conda.pydata.org/docs/py2or3.html) to add a 2.7 environment and activate it. Then I verified I was using "snakes" and installed kivy using the instructions [here](https://kivy.org/docs/installation/installation-osx.html#using-homebrew-with-pip) -- the pre-reqs were already installed so I just needed the pip commands. Reinstalled simplejson using pip. Works fine, though there's a text size issue I'll look at shortly.

**Comment by Sektor527** [comment]
I managed to get it working now, properly invoking python 2.

The problem existed with my windows environment, totally my fault. A few days ago, I thought to be clever by creating a Windows file association for .py files, pointing to my standard Python 3, so that I didn't have to type the 'python' command all the time but could simply invoke it by calling the script name. I failed to realize that that, of course, totally ignores a conda environment.

I'm sorry for wasting your time like that :/

**Comment by exposit** [comment]
Oh, not a waste at all! I noticed a weird text sizing issue when I launched through Anaconda that wasn't occurring in my usual Python install. Turns out that I needed to reconfigure all declared sizes using "dp" instead of just flat px, so now it should rescale much more nicely if people aren't using the same resolution as I am. Well, except for the bits I probably missed, hahaha!
